/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugTrackingRouteImport } from './routes/debug-tracking'
import { Route as Etapa2RouteImport } from './routes/etapa-2'
import { Route as Etapa3RouteImport } from './routes/etapa-3'
import { Route as Etapa4RouteImport } from './routes/etapa-4'
import { Route as Etapa5RouteImport } from './routes/etapa-5'
import { Route as Etapa6RouteImport } from './routes/etapa-6'
import { Route as Etapa7RouteImport } from './routes/etapa-7'
import { Route as Etapa8RouteImport } from './routes/etapa-8'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as OfertaEspecialRouteImport } from './routes/oferta-especial'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as ApiPublicRecuperarPagamentosRouteImport } from './routes/api/public/recuperar-pagamentos'
import { Route as ApiPublicReenviarUtmifyRouteImport } from './routes/api/public/reenviar-utmify'
import { Route as ApiPublicTesteUtmifyRouteImport } from './routes/api/public/teste-utmify'
import { Route as ApiPublicWebhookPagamentoRouteImport } from './routes/api/public/webhook-pagamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugTrackingRoute = DebugTrackingRouteImport.update({
  id: '/debug-tracking',
  path: '/debug-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const Etapa2Route = Etapa2RouteImport.update({
  id: '/etapa-2',
  path: '/etapa-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Etapa3Route = Etapa3RouteImport.update({
  id: '/etapa-3',
  path: '/etapa-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Etapa4Route = Etapa4RouteImport.update({
  id: '/etapa-4',
  path: '/etapa-4',
  getParentRoute: () => rootRouteImport,
} as any)
const Etapa5Route = Etapa5RouteImport.update({
  id: '/etapa-5',
  path: '/etapa-5',
  getParentRoute: () => rootRouteImport,
} as any)
const Etapa6Route = Etapa6RouteImport.update({
  id: '/etapa-6',
  path: '/etapa-6',
  getParentRoute: () => rootRouteImport,
} as any)
const Etapa7Route = Etapa7RouteImport.update({
  id: '/etapa-7',
  path: '/etapa-7',
  getParentRoute: () => rootRouteImport,
} as any)
const Etapa8Route = Etapa8RouteImport.update({
  id: '/etapa-8',
  path: '/etapa-8',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaEspecialRoute = OfertaEspecialRouteImport.update({
  id: '/oferta-especial',
  path: '/oferta-especial',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecuperarPagamentosRoute =
  ApiPublicRecuperarPagamentosRouteImport.update({
    id: '/api/public/recuperar-pagamentos',
    path: '/api/public/recuperar-pagamentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReenviarUtmifyRoute = ApiPublicReenviarUtmifyRouteImport.update({
  id: '/api/public/reenviar-utmify',
  path: '/api/public/reenviar-utmify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTesteUtmifyRoute = ApiPublicTesteUtmifyRouteImport.update({
  id: '/api/public/teste-utmify',
  path: '/api/public/teste-utmify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookPagamentoRoute =
  ApiPublicWebhookPagamentoRouteImport.update({
    id: '/api/public/webhook-pagamento',
    path: '/api/public/webhook-pagamento',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug-tracking': typeof DebugTrackingRoute
  '/etapa-2': typeof Etapa2Route
  '/etapa-3': typeof Etapa3Route
  '/etapa-4': typeof Etapa4Route
  '/etapa-5': typeof Etapa5Route
  '/etapa-6': typeof Etapa6Route
  '/etapa-7': typeof Etapa7Route
  '/etapa-8': typeof Etapa8Route
  '/funil': typeof FunilRoute
  '/oferta-especial': typeof OfertaEspecialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/public/recuperar-pagamentos': typeof ApiPublicRecuperarPagamentosRoute
  '/api/public/reenviar-utmify': typeof ApiPublicReenviarUtmifyRoute
  '/api/public/teste-utmify': typeof ApiPublicTesteUtmifyRoute
  '/api/public/webhook-pagamento': typeof ApiPublicWebhookPagamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug-tracking': typeof DebugTrackingRoute
  '/etapa-2': typeof Etapa2Route
  '/etapa-3': typeof Etapa3Route
  '/etapa-4': typeof Etapa4Route
  '/etapa-5': typeof Etapa5Route
  '/etapa-6': typeof Etapa6Route
  '/etapa-7': typeof Etapa7Route
  '/etapa-8': typeof Etapa8Route
  '/funil': typeof FunilRoute
  '/oferta-especial': typeof OfertaEspecialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/public/recuperar-pagamentos': typeof ApiPublicRecuperarPagamentosRoute
  '/api/public/reenviar-utmify': typeof ApiPublicReenviarUtmifyRoute
  '/api/public/teste-utmify': typeof ApiPublicTesteUtmifyRoute
  '/api/public/webhook-pagamento': typeof ApiPublicWebhookPagamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug-tracking': typeof DebugTrackingRoute
  '/etapa-2': typeof Etapa2Route
  '/etapa-3': typeof Etapa3Route
  '/etapa-4': typeof Etapa4Route
  '/etapa-5': typeof Etapa5Route
  '/etapa-6': typeof Etapa6Route
  '/etapa-7': typeof Etapa7Route
  '/etapa-8': typeof Etapa8Route
  '/funil': typeof FunilRoute
  '/oferta-especial': typeof OfertaEspecialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/public/recuperar-pagamentos': typeof ApiPublicRecuperarPagamentosRoute
  '/api/public/reenviar-utmify': typeof ApiPublicReenviarUtmifyRoute
  '/api/public/teste-utmify': typeof ApiPublicTesteUtmifyRoute
  '/api/public/webhook-pagamento': typeof ApiPublicWebhookPagamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug-tracking'
    | '/etapa-2'
    | '/etapa-3'
    | '/etapa-4'
    | '/etapa-5'
    | '/etapa-6'
    | '/etapa-7'
    | '/etapa-8'
    | '/funil'
    | '/oferta-especial'
    | '/privacidade'
    | '/termos-de-uso'
    | '/api/public/recuperar-pagamentos'
    | '/api/public/reenviar-utmify'
    | '/api/public/teste-utmify'
    | '/api/public/webhook-pagamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug-tracking'
    | '/etapa-2'
    | '/etapa-3'
    | '/etapa-4'
    | '/etapa-5'
    | '/etapa-6'
    | '/etapa-7'
    | '/etapa-8'
    | '/funil'
    | '/oferta-especial'
    | '/privacidade'
    | '/termos-de-uso'
    | '/api/public/recuperar-pagamentos'
    | '/api/public/reenviar-utmify'
    | '/api/public/teste-utmify'
    | '/api/public/webhook-pagamento'
  id:
    | '__root__'
    | '/'
    | '/debug-tracking'
    | '/etapa-2'
    | '/etapa-3'
    | '/etapa-4'
    | '/etapa-5'
    | '/etapa-6'
    | '/etapa-7'
    | '/etapa-8'
    | '/funil'
    | '/oferta-especial'
    | '/privacidade'
    | '/termos-de-uso'
    | '/api/public/recuperar-pagamentos'
    | '/api/public/reenviar-utmify'
    | '/api/public/teste-utmify'
    | '/api/public/webhook-pagamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugTrackingRoute: typeof DebugTrackingRoute
  Etapa2Route: typeof Etapa2Route
  Etapa3Route: typeof Etapa3Route
  Etapa4Route: typeof Etapa4Route
  Etapa5Route: typeof Etapa5Route
  Etapa6Route: typeof Etapa6Route
  Etapa7Route: typeof Etapa7Route
  Etapa8Route: typeof Etapa8Route
  FunilRoute: typeof FunilRoute
  OfertaEspecialRoute: typeof OfertaEspecialRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ApiPublicRecuperarPagamentosRoute: typeof ApiPublicRecuperarPagamentosRoute
  ApiPublicReenviarUtmifyRoute: typeof ApiPublicReenviarUtmifyRoute
  ApiPublicTesteUtmifyRoute: typeof ApiPublicTesteUtmifyRoute
  ApiPublicWebhookPagamentoRoute: typeof ApiPublicWebhookPagamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-tracking': {
      id: '/debug-tracking'
      path: '/debug-tracking'
      fullPath: '/debug-tracking'
      preLoaderRoute: typeof DebugTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapa-2': {
      id: '/etapa-2'
      path: '/etapa-2'
      fullPath: '/etapa-2'
      preLoaderRoute: typeof Etapa2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapa-3': {
      id: '/etapa-3'
      path: '/etapa-3'
      fullPath: '/etapa-3'
      preLoaderRoute: typeof Etapa3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapa-4': {
      id: '/etapa-4'
      path: '/etapa-4'
      fullPath: '/etapa-4'
      preLoaderRoute: typeof Etapa4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapa-5': {
      id: '/etapa-5'
      path: '/etapa-5'
      fullPath: '/etapa-5'
      preLoaderRoute: typeof Etapa5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapa-6': {
      id: '/etapa-6'
      path: '/etapa-6'
      fullPath: '/etapa-6'
      preLoaderRoute: typeof Etapa6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapa-7': {
      id: '/etapa-7'
      path: '/etapa-7'
      fullPath: '/etapa-7'
      preLoaderRoute: typeof Etapa7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapa-8': {
      id: '/etapa-8'
      path: '/etapa-8'
      fullPath: '/etapa-8'
      preLoaderRoute: typeof Etapa8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta-especial': {
      id: '/oferta-especial'
      path: '/oferta-especial'
      fullPath: '/oferta-especial'
      preLoaderRoute: typeof OfertaEspecialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recuperar-pagamentos': {
      id: '/api/public/recuperar-pagamentos'
      path: '/api/public/recuperar-pagamentos'
      fullPath: '/api/public/recuperar-pagamentos'
      preLoaderRoute: typeof ApiPublicRecuperarPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reenviar-utmify': {
      id: '/api/public/reenviar-utmify'
      path: '/api/public/reenviar-utmify'
      fullPath: '/api/public/reenviar-utmify'
      preLoaderRoute: typeof ApiPublicReenviarUtmifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/teste-utmify': {
      id: '/api/public/teste-utmify'
      path: '/api/public/teste-utmify'
      fullPath: '/api/public/teste-utmify'
      preLoaderRoute: typeof ApiPublicTesteUtmifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook-pagamento': {
      id: '/api/public/webhook-pagamento'
      path: '/api/public/webhook-pagamento'
      fullPath: '/api/public/webhook-pagamento'
      preLoaderRoute: typeof ApiPublicWebhookPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugTrackingRoute: DebugTrackingRoute,
  Etapa2Route: Etapa2Route,
  Etapa3Route: Etapa3Route,
  Etapa4Route: Etapa4Route,
  Etapa5Route: Etapa5Route,
  Etapa6Route: Etapa6Route,
  Etapa7Route: Etapa7Route,
  Etapa8Route: Etapa8Route,
  FunilRoute: FunilRoute,
  OfertaEspecialRoute: OfertaEspecialRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ApiPublicRecuperarPagamentosRoute: ApiPublicRecuperarPagamentosRoute,
  ApiPublicReenviarUtmifyRoute: ApiPublicReenviarUtmifyRoute,
  ApiPublicTesteUtmifyRoute: ApiPublicTesteUtmifyRoute,
  ApiPublicWebhookPagamentoRoute: ApiPublicWebhookPagamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
